dist: xenial
language: python
python:
  - "3.7"
install:
  - "pip install pytest lxml"
  - "python setup.py develop"
script:
  - "pytest"
deploy:
  on:
    repo: Toblerity/keytree
    python: 3.7
    tags: true
  provider: pypi
  distributions: "sdist bdist_wheel"
  user: __token__
